name: Main

on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Download go modules
        run: go mod download

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linters
        uses: reviewdog/action-golangci-lint@v2
        with:
          filter_mode: nofilter

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ build ]
    services:
      cache:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Docker
        run: |
          docker create --name redis_cluster \
          -p 7001-7006:7001-7006 \
          --health-cmd "redis-cli -c -p 7001 ping" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5 \
          -e "INITIAL_PORT=7001" \
          -e "BIND_ADDRESS=0.0.0.0" \
          -e "MASTERS=3" \
          -e "SLAVES_PER_MASTER=1" \
          -v ${{ github.workspace }}/.github/workflows/redis-cluster.tmpl:/redis-conf/redis-cluster.tmpl \
          grokzen/redis-cluster:7.0.7
          docker start redis_cluster
      - name: Test
        run: go test -v ./...
